# Generated by Django 3.2.5 on 2023-05-18 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20230519_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercoin',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='coin_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
