# Generated by Django 3.2.5 on 2023-06-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0006_usercoin_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
