# Generated by Django 3.2.5 on 2023-06-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0007_usercoin_manual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('user_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.usercoin')),
            ],
        ),
        migrations.DeleteModel(
            name='CoinHistory',
        ),
    ]
